module.exports = {
  '../../jade/header.jade': require('../../jade/header.jade'),
  '../../jade/clients/client.jade': require('../../jade/clients/client.jade'),
  '../../jade/clients/clients.jade': require('../../jade/clients/clients.jade'),
  '../../jade/clients/invoice.jade': require('../../jade/clients/invoice.jade'),
  '../../jade/clients/invoices.jade': require('../../jade/clients/invoices.jade'),
  '../../jade/editor/details.jade': require('../../jade/editor/details.jade'),
  '../../jade/editor/header.jade': require('../../jade/editor/header.jade'),
  '../../jade/editor/row_bullet.jade': require('../../jade/editor/row_bullet.jade'),
  '../../jade/editor/row_date.jade': require('../../jade/editor/row_date.jade'),
  '../../jade/editor/row_heading.jade': require('../../jade/editor/row_heading.jade'),
  '../../jade/editor/row_item.jade': require('../../jade/editor/row_item.jade'),
  '../../jade/pages/clients.jade': require('../../jade/pages/clients.jade'),
  '../../jade/pages/editor.jade': require('../../jade/pages/editor.jade'),
  '../../jade/pages/invoices.jade': require('../../jade/pages/invoices.jade'),
  '../../jade/pages/settings.jade': require('../../jade/pages/settings.jade'),
};
